## 練習時間
在小量的資料上，我們用眼睛就可以看得出來程式碼是否有跑出我們理想中的結果

請嘗試想像一個你需要的資料結構 (裡面的值可以是隨機的)，然後用上述的方法把它變成 pandas DataFrame

#### Ex: 想像一個 dataframe 有兩個欄位，一個是國家，一個是人口，求人口數最多的國家

### Hints: [隨機產生數值](https://blog.csdn.net/christianashannon/article/details/78867204)

In [21]:
import pandas as pd
import numpy as np

In [25]:
#從txt檔案讀取國家名稱

國家 = []
with open("data/country_list.txt", 'r') as f:
    data_tmp = f.readlines()

#去掉每一個element的'/n'

for i in data_tmp:
    國家.append(i.strip())

#隨機產生相對應的國家人口數

total_country = len(國家)
人口 = np.random.randint(10000, 1000000000, total_country)

#將國家和人口組成一個array

data = {'國家':國家, '人口':人口}

#格式化成一個data frame
final_data = pd.DataFrame(data)

pd.set_option('display.max_rows', total_country)
print(final_data)

                                    國家         人口
0                          Afghanistan  679990504
1                              Albania  898512996
2                              Algeria   63587363
3                              Andorra  416607832
4                               Angola   80121152
5                  Antigua and Barbuda    7073076
6                            Argentina  168600512
7                              Armenia  754022710
8                                Aruba   37749942
9                            Australia  342518555
10                             Austria   32919307
11                          Azerbaijan  514407647
12                             Bahamas  512746345
13                             Bahrain  595165262
14                          Bangladesh  427140151
15                            Barbados  423557400
16                             Belarus  267617171
17                             Belgium  751721983
18                              Belize   93715468
19                               Benin  359517323
20                              Bhutan  717611714
21                             Bolivia  918924000
22              Bosnia and Herzegovina  669896722
23                            Botswana  129329430
24                              Brazil   78692907
25                              Brunei  803139156
26                            Bulgaria  314578829
27                        Burkina Faso  517788156
28                               Burma  433642864
29                             Burundi  538436430
30                            Cambodia  507738702
31                            Cameroon  261733967
32                              Canada  248668135
33                          Cabo Verde   50084056
34            Central African Republic  445417385
35                                Chad  660789489
36                               Chile  786170879
37                               China  840348312
38                            Colombia  937466139
39                             Comoros  588817139
40   Congo, Democratic Republic of the  208508268
41              Congo, Republic of the  602441260
42                          Costa Rica  391986053
43                       Cote d'Ivoire  504375251
44                             Croatia  649631693
45                                Cuba  809160471
46                             Curacao   30185113
47                              Cyprus  430708127
48                             Czechia  407888329
49                             Denmark  589953200
50                            Djibouti  140218968
51                            Dominica  535648869
52                  Dominican Republic  538344376
53                          East Timor  732956624
54                             Ecuador  226111698
55                               Egypt   98938751
56                         El Salvador  416630413
57                   Equatorial Guinea  372479425
58                             Eritrea  226677365
59                             Estonia  470961496
60                            Eswatini  618638596
61                            Ethiopia  994462633
62                                Fiji  717780148
63                             Finland  903176937
64                              France  536206924
65                               Gabon  819434003
66                         Gambia, The  371204698
67                             Georgia  107380633
68                             Germany  715189237
69                               Ghana  265272246
70                              Greece  578386211
71                             Grenada  792211423
72                           Guatemala  721465216
73                              Guinea  119130764
74                       Guinea-Bissau  515535139
75                              Guyana  657681462
76                               Haiti  359968616
77                            Holy See  479044552
78                            Honduras  587980096
79                           Hong Kong  185809986
80                             Hungary  732226002
81                             Iceland   38068755
82                               India  173989481
83                           Indonesia  734756405
84                                Iran  587408064
85                                Iraq  167345724
86                             Ireland  524475360
87                              Israel  924513059
88                               Italy  262460828
89                             Jamaica  153427225
90                               Japan  312216158
91                              Jordan  785443349
92                          Kazakhstan  392829868
93                               Kenya  672794914
94                            Kiribati  257396712
95                        Korea, North  768859479
96                        Korea, South  367471816
97                              Kosovo  202795377
98                              Kuwait  795769123
99                          Kyrgyzstan  386799013
100                               Laos  227577717
101                             Latvia  206246525
102                            Lebanon  241515692
103                            Lesotho   74176622
104                            Liberia  225783047
105                              Libya  936549647
106                      Liechtenstein  228789629
107                          Lithuania  491367057
108                         Luxembourg  799208711
109                              Macau  654126951
110                         Madagascar  126300104
111                             Malawi  466251247
112                           Malaysia   93047929
113                           Maldives  738700787
114                               Mali  913104324
115                              Malta  350245225
116                   Marshall Islands  177490281
117                         Mauritania  360507009
118                          Mauritius  809219149
119                             Mexico  707020890
120                         Micronesia  363455047
121                            Moldova  583517703
122                             Monaco  401932950
123                           Mongolia  848197661
124                         Montenegro  872080854
125                            Morocco  422171605
126                         Mozambique  364783220
127                            Namibia  937285356
128                              Nauru  327110336
129                              Nepal  993912126
130                        Netherlands  732037452
131                        New Zealand  767440878
132                          Nicaragua  167294394
133                              Niger   61035826
134                            Nigeria  299459408
135                        North Korea  757705599
136                    North Macedonia  869243930
137                             Norway  399633579
138                               Oman  324961347
139                           Pakistan  285178173
140                              Palau  556001255
141            Palestinian Territories  750272219
142                             Panama   93013528
143                   Papua New Guinea   35341524
144                           Paraguay  215310688
145                               Peru  689042916
146                        Philippines  806995080
147                             Poland  701814266
148                           Portugal  825238525
149                              Qatar  734435033
150                            Romania  417421278
151                             Russia  772736616
152                             Rwanda   37997352
153              Saint Kitts and Nevis  746027109
154                        Saint Lucia  974545913
155   Saint Vincent and the Grenadines  867952142
156                              Samoa  760218124
157                         San Marino  480516917
158              Sao Tome and Principe  710497912
159                       Saudi Arabia  426770956
160                            Senegal  835792621
161                             Serbia  646951165
162                         Seychelles  569417043
163                       Sierra Leone  176317902
164                          Singapore  228990295
165                       Sint Maarten  697118904
166                           Slovakia  804526389
167                           Slovenia  682768180
168                    Solomon Islands  374549521
169                            Somalia  847369688
170                       South Africa  577876360
171                        South Korea  990568586
172                        South Sudan  137937592
173                              Spain  627602223
174                          Sri Lanka   99546032
175                              Sudan  965199725
176                           Suriname  877592585
177                          Swaziland   12427911
178                             Sweden  483966612
179                        Switzerland  216187219
180                              Syria  812419677
181                             Taiwan  621777537
182                         Tajikistan  493554566
183                           Tanzania  677096167
184                           Thailand  946035408
185                        Timor-Leste   22090552
186                               Togo  868360535
187                              Tonga  373178345
188                Trinidad and Tobago  280932469
189                            Tunisia  413049483
190                             Turkey  943860256
191                       Turkmenistan  269932211
192                             Tuvalu   60517014
193                             Uganda   41245826
194                            Ukraine  960745283
195               United Arab Emirates  144519260
196                     United Kingdom  835749764
197                            Uruguay   10922817
198                         Uzbekistan  901126050
199                            Vanuatu  545354915
200                          Venezuela  510038174
201                            Vietnam  472207243
202                              Yemen  710901741
203                             Zambia   16086875
204                           Zimbabwe  110575971

In [26]:
#找出人口數最多的國家

max_people_idx_num = final_data['人口'].idxmax()
data_content = final_data.iloc[max_people_idx_num]
print(data_content)

國家     Ethiopia
人口    994462633
Name: 61, dtype: object